import Foundation

/// Real server responses for the AI button, generated by apps/api/test/iosFixtures.test.ts from the app's own
/// sample places. Swift tests decode them; DEBUG screenshot scenarios replay them.
enum AIFixtures {
  static func data(_ name: String) -> Data? {
    guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Resources/ai-fixtures")
    else { return nil }
    return try? Data(contentsOf: url)
  }

  static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
    guard let data = data(name) else { throw CocoaError(.fileNoSuchFile, userInfo: [NSFilePathErrorKey: name]) }
    return try HermiAPI.decoder.decode(T.self, from: data)
  }
}
